// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWPEjteMRcXF_r0yw9ElhAPS6DxSIESLU',
    appId: '1:126732798243:web:6e335e2e72ce1403fd2496',
    messagingSenderId: '126732798243',
    projectId: 'kltn-d256a',
    authDomain: 'kltn-d256a.firebaseapp.com',
    storageBucket: 'kltn-d256a.firebasestorage.app',
    measurementId: 'G-L93NJRXGXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgp7X_CFZsPKCLCox6htHPLEthkllHuqY',
    appId: '1:126732798243:android:50fcbcd82f834467fd2496',
    messagingSenderId: '126732798243',
    projectId: 'kltn-d256a',
    storageBucket: 'kltn-d256a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxDEzPIexeN4Vj_bMJ5KMLBb9zalhl6eg',
    appId: '1:126732798243:ios:4025795675a52cd0fd2496',
    messagingSenderId: '126732798243',
    projectId: 'kltn-d256a',
    storageBucket: 'kltn-d256a.firebasestorage.app',
    iosBundleId: 'com.example.se501Plantheon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxDEzPIexeN4Vj_bMJ5KMLBb9zalhl6eg',
    appId: '1:126732798243:ios:4025795675a52cd0fd2496',
    messagingSenderId: '126732798243',
    projectId: 'kltn-d256a',
    storageBucket: 'kltn-d256a.firebasestorage.app',
    iosBundleId: 'com.example.se501Plantheon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWPEjteMRcXF_r0yw9ElhAPS6DxSIESLU',
    appId: '1:126732798243:web:a6627b0411133d48fd2496',
    messagingSenderId: '126732798243',
    projectId: 'kltn-d256a',
    authDomain: 'kltn-d256a.firebaseapp.com',
    storageBucket: 'kltn-d256a.firebasestorage.app',
    measurementId: 'G-EKWPHR54RN',
  );
}
